routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Route::get('/categories', 'CategoryController@index')->name('categories');
Route::get('/categories/{id}', 'CategoryController@detail')->name('categories-detail');

Route::get('/rewards', 'RewardsController@index')->name('rewards');

Route::get('/details/{id}', 'DetailController@index')->name('detail');
Route::post('/details/{id}', 'DetailController@add')->name('detail-add');

Route::post('/checkout/callback', 'CheckoutController@callback')->name('midtrans-callback');

Route::get('/success', 'CartController@success')->name('success');

Route::get('/register/success', 'Auth\RegisterController@success')->name('register-success');

Route::group(['middleware' => ['auth']], function () {
  Route::get('/cart', 'CartController@index')->name('cart');
  Route::delete('/cart/{id}', 'CartController@delete')->name('cart-delete');

  Route::post('/checkout', 'CheckoutController@process')->name('checkout');

  // Dashboard User
  Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

  Route::get('/dashboard/products', 'DashboardProductController@index')->name('dashboard-product');
  Route::post('/dashboard/products', 'DashboardProductController@store')->name('dashboard-product-store');
  Route::get('/dashboard/products/create', 'DashboardProductController@create')->name('dashboard-product-create');
  Route::get('/dashboard/products/{id}', 'DashboardProductController@details')->name('dashboard-product-details');
  Route::post('/dashboard/products/{id}', 'DashboardProductController@update')->name('dashboard-product-update');

  Route::post('/dashboard/products/gallery/upload', 'DashboardProductController@uploadGallery')->name('dashboard-product-gallery-upload');
  Route::get('/dashboard/products/gallery/delete/{id}', 'DashboardProductController@deleteGallery')->name('dashboard-product-gallery-delete');

  Route::get('/dashboard/transactions', 'DashboardTransactionController@index')->name('dashboard-transaction');
  Route::get('/dashboard/transactions/{id}', 'DashboardTransactionController@details')->name('dashboard-transaction-details');
  Route::post('/dashboard/transactions/{id}', 'DashboardTransactionController@update')->name('dashboard-transaction-update');

  Route::get('/dashboard/settings', 'DashboardSettingController@store')->name('dashboard-settings-store');
  Route::get('/dashboard/account', 'DashboardSettingController@account')->name('dashboard-settings-account');
  Route::post('/dashboard/account/{redirect}', 'DashboardSettingController@update')->name('dashboard-settings-redirect');
});

// For Admin
Route::prefix('admin')->namespace('Admin')->middleware('auth', 'admin')->group(function () {
  Route::get('/', 'DashboardController@index')->name('admin-dashboard');
  Route::resource('category', 'CategoryController');
  Route::resource('user', 'UserController');
  Route::resource('product', 'ProductController');
  Route::resource('product-gallery', 'ProductGalleryController');
});

Auth::routes();

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use SoftDeletes;

    // Proctected fillable fields
    protected $fillable = [
        'name',
        'photo',
        'slug',
    ];

    // menyembunyikan model saat di panggil
    protected $hidden = [];
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

use App\Http\Requests\Admin\CategoryRequest;

use App\Http\Controllers\Controller;
use Yajra\DataTables\Facades\DataTables;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // mengecek apakah memanggil ajax atau bukan
        if (request()->ajax()) {
            // memanggil query untuk model category
            $query = Category::query();

            return DataTables::of($query)
                ->addColumn('action', function ($item) {
                    return ' 
                    <div class="btn-group">
                        <div class="dropdown">
                        <button class="btn btn-success dropdown-toggle mr-1 mb-1" type="button" data-toggle="dropdown">Action</button>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="' . route('category.edit', $item->id) . '">Edit</a>
                                <form method="post" action="' . route('category.destroy', $item->id) . '">
                                ' . method_field('DELETE') . csrf_field() . '
                                <button class="dropdown-item text-danger" type="submit">Delete</button>
                                </form>
                            </div>
                        </div>
                    </div>
                    ';
                })
                ->editColumn('photo', function ($item) {
                    return $item->photo ? '<img src="' . Storage::url($item->photo) . '" style="max-height: 50px;" />' : '';
                })
                ->rawColumns(['action', 'photo'])
                ->make();
        }
        return view('pages.admin.category.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.admin.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  App\Http\Requests\Admin\CategoryRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {
        $data = $request->all();

        $data['slug'] = Str::slug($request->name);
        $data['photo'] = $request->file('photo')->store('assets/category', 'public');

        Category::create($data);

        return redirect()->route('category.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = Category::findOrFail($id);

        return view('pages.admin.category.edit', [
            'item' => $item,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  App\Http\Requests\Admin\CategoryRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryRequest $request, $id)
    {
        $data = $request->all();

        $data['slug'] = Str::slug($request->name);
        // jika perbaharui data tanpa ganti photo
        if (!$request->hasFile('photo')) {
            $data['photo'] = Category::findOrFail($id)->photo;
            // jika ganti photo, hapus foto lama
        } elseif (!empty($request->file('photo')) && $request->file('photo')->isValid()) {
            // simpan photo baru
            $data['photo'] = $request->file('photo')->store('assets/category', 'public');
            // hapus photo lama
            $oldPhoto = Category::findOrFail($id)->photo;
            Storage::delete('public/' . $oldPhoto);
        }

        $item = Category::findOrFail($id);
        $item->update($data);

        return redirect()->route('category.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // hapus data dengan menghapus photo
        $item = Category::findOrFail($id);
        $oldPhoto = $item->photo;
        $item->delete();
        Storage::delete('public/' . $oldPhoto);
        // kembali ke halaman index
        return redirect()->route('category.index');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Category;
use App\Product;

class CategoryController extends Controller
{
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        // Mengambil data Category
        $categories = Category::all();
        // Mengambil data product dan merelasikan ke tabel product_galleries dengan pagination
        $products = Product::with(['galleries'])->paginate(16);

        return view('pages.category', [
            'categories' => $categories,
            'products' => $products
        ]);
    }

    public function detail(Request $request, $slug)
    {
        $categories = Category::all();
        $category = Category::where('slug', $slug)->firstOrFail();
        $products = Product::with(['galleries'])->where('categories_id', $category->id)->paginate(16);

        return view('pages.category', [
            'categories' => $categories,
            'products' => $products
        ]);
    }
}

resources/views/pages/admin/category/create.blade.php
@extends('layouts.admin')

@section('title')
Category | Create
@endsection

@section('content')
{{-- Section Content --}}
<div class="section-content section-dashboard-home" data-aos="fade-up">
  <div class="container-fluid">
    <div class="dashboard-heading">
      <h2 class="dashboard-title">Category</h2>
      <p class="dashboard-subtitle">Create new category</p>
    </div>
    <div class="dashboard-content">
      <div class="row">
        <div class="col-md-12">
          @if($errors->any())
          <div class="alert alert-danger">
            @foreach($errors->all() as $error)
            {{ $error }}
            @endforeach
          </div>
          @endif
          <div class="card">
            <div class="card-body">
              <form action="{{ route('category.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="row">
                  <div class="col-md-12">
                    <div class="form-group">
                      <label for="">Nama Kategori</label>
                      <input type="text" name="name" class="form-control" id="" placeholder="Nama Kategori" required>
                    </div>
                  </div>
                  <div class="col-md-12">
                    <div class="form-group">
                      <label for="">Foto</label>
                      <input type="file" name="photo" class="form-control" id="" placeholder="Foto" required>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col text-right">
                    <button type="submit" class="btn btn-success px-5 mt-3">Save Now</button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

@push('addon-script')
<script>
  window.setTimeout(function() {
    $(".alert").fadeTo(500, 0).slideUp(500, function() {
      $(this).remove();
    });
  }, 3000);
</script>
@endpush

resources/views/pages/admin/category/edit.blade.php
@extends('layouts.admin')

@section('title')
Category | Edit
@endsection

@section('content')
{{-- Section Content --}}
<div class="section-content section-dashboard-home" data-aos="fade-up">
  <div class="container-fluid">
    <div class="dashboard-heading">
      <h2 class="dashboard-title">Category</h2>
      <p class="dashboard-subtitle">Edit new category</p>
    </div>
    <div class="dashboard-content">
      <div class="row">
        <div class="col-md-12">
          @if($errors->any())
          <div class="alert alert-danger">
            @foreach($errors->all() as $error)
            {{ $error }}
            @endforeach
          </div>
          @endif
          <div class="card">
            <div class="card-body">
              <form action="{{ route('category.update', $item->id) }}" method="POST" enctype="multipart/form-data">
                @method('PUT')
                @csrf
                <div class="row">
                  <div class="col-md-12">
                    <div class="form-group">
                      <label for="">Nama Kategori</label>
                      <input type="text" name="name" class="form-control" id="" placeholder="Nama Kategori"
                        value="{{ $item->name }}" required>
                    </div>
                  </div>
                  <div class="col-md-12">
                    <div class="form-group">
                      <label for="">Foto</label>
                      <input type="file" name="photo" class="form-control" id="" placeholder="Foto">
                      <i style="font-size: 12px;">
                        <sup class="text-danger">*</sup>
                        Just leave it blank if you don't wantto change the image.
                      </i>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col text-right">
                    <button type="submit" class="btn btn-success px-5 mt-3">Save Now</button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

@push('addon-script')
<script>
  window.setTimeout(function() {
    $(".alert").fadeTo(500, 0).slideUp(500, function() {
      $(this).remove();
    });
  }, 3000);
</script>
@endpush

resources/views/pages/admin/category/index.blade.php
@extends('layouts.admin')

@section('title')
Dashboard | Category
@endsection

@section('content')
{{-- Section Content --}}
<div class="section-content section-dashboard-home" data-aos="fade-up">
  <div class="container-fluid">
    <div class="dashboard-heading">
      <h2 class="dashboard-title">Category</h2>
      <p class="dashboard-subtitle">List of category</p>
    </div>
    <div class="dashboard-content">
      <div class="row">
        <div class="col-md-12">
          <div class="card">
            <div class="card-body">
              <a href="{{ route('category.create') }}" class="btn btn-success mb-3">
                <i class="fas fa-plus-circle"></i> Add Category
              </a>
              <div class="table-responsive">
                <table class="table table-hover scroll-horizontal-vertical w-100" id="crudTable">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>Nama</th>
                      <th>Foto</th>
                      <th>Slug</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

@push('addon-script')
<script>
  // Datatable
      $(document).ready(function() {
        $('#crudTable').DataTable({
          processing: true,
          serverSide: true,
          ordering: true,

          ajax: {
            url: '{!! url()->current() !!}',
          },
          columns: [
            { data: 'id', name: 'id' },
            { data: 'name', name: 'name' },
            { data: 'photo', name: 'photo' },
            { data: 'slug', name: 'slug' },
            { 
              data: 'action',
              name: 'action',
              orderable: false,
              searchable: false,
              width: '15%'
            }
          ]
        });
      });
</script>
@endpush